# Generated by Django 5.2.7 on 2025-10-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_harga_remove_event_maksimal_peserta'),
        ('ticketing', '0004_alter_booking_total_price_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('event', 'ticket_type')},
        ),
    ]
