# Generated by Django 5.2.7 on 2025-10-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_category_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('sepakbola', 'Sepakbola'), ('f1', 'F1'), ('moto gp', 'Moto GP'), ('raket', 'Raket'), ('olahraga lain', 'Olahraga Lain')], default='sepakbola', max_length=50),
        ),
    ]
