# Generated by Django 5.2.7 on 2025-10-22 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('date', models.DateTimeField()),
                ('harga', models.IntegerField(default=0)),
                ('lokasi', models.CharField(max_length=300)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_views', models.PositiveIntegerField(default=0)),
                ('kategori', models.CharField(choices=[('basket', 'Basket'), ('tennis', 'Tennis'), ('bulu tangkis', 'Bulu Tangkis'), ('volley', 'Volley'), ('futsal', 'Futsal'), ('sepak bola', 'Sepak Bola'), ('renang', 'Renang'), ('lainnya', 'Lainnya')], default='basket', max_length=20)),
                ('maksimal_peserta', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
