# Generated by Django 5.2.7 on 2025-10-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('basket', 'Basket'), ('tennis', 'Tennis'), ('bulu tangkis', 'Bulu Tangkis'), ('volley', 'Volley'), ('futsal', 'Futsal'), ('sepak bola', 'Sepak Bola'), ('renang', 'Renang'), ('lainnya', 'Lainnya')], default='basket', max_length=20),
        ),
    ]
