# Generated by Django 5.2.7 on 2025-10-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='event',
            name='maksimal_peserta',
        ),
    ]
