# Generated by Django 5.2.7 on 2025-10-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='price',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='judul',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='kategori',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='lokasi',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Max_participants',
            new_name='maksimal_peserta',
        ),
    ]
