# Generated by Django 5.2.7 on 2025-10-22 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_views', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('basket', 'Basket'), ('tennis', 'Tennis'), ('padel', 'Padel'), ('badminton', 'Badminton'), ('cricket', 'Cricket'), ('volleyball', 'Volleyball')], default='update', max_length=20)),
                ('Max_participants', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
