# Generated by Django 5.2.7 on 2025-10-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('basket', 'Basket'), ('tennis', 'Tennis'), ('padel', 'Padel'), ('badminton', 'Badminton'), ('cricket', 'Cricket'), ('volleyball', 'Volleyball')], default='basket', max_length=20),
        ),
    ]
