# Generated by Django 5.2.7 on 2025-11-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumdiskusi', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumdiskusi',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='news.article'),
        ),
    ]
