# Generated by Django 5.2.7 on 2025-10-22 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumdiskusi', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='forumdiskusi',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_diskusi', to='news.article'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
