# Generated by Django 5.2.7 on 2025-10-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumdiskusi', '0003_alter_post_options_forumdiskusi_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
