# Generated by Django 5.2.7 on 2025-10-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_userprofile_booked_events_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='post_created',
            new_name='komentar_created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='booked_events',
        ),
    ]
