# Generated by Django 5.2.7 on 2025-10-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0005_status_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='komentar_created',
            new_name='events_created',
        ),
    ]
