# Generated by Django 5.2.7 on 2025-10-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0010_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
