# Generated by Django 5.2.7 on 2025-10-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0011_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='events_created',
            new_name='komentar_created',
        ),
    ]
