# Generated by Django 5.2.7 on 2025-10-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0012_rename_events_created_userprofile_komentar_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='komentar_created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='news_created',
        ),
    ]
