# Generated by Django 5.2.7 on 2025-11-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0015_userprofile_events_created_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='news_created',
            field=models.IntegerField(default=0),
        ),
    ]
